name: First action
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: greeting
        run: echo "Hello World"
      - name: another msg
        run: echo "Hello from the other side"
